Prepare csv files downloaded from PubChem database

In [ ]:
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/final_project/new_split/finaldataset.csv')
#df = pd.read_csv('/content/drive/MyDrive/final_project/new_split/actives.csv')

In [ ]:
df #display dataset containing compound cid and smiles and activity class

,Smiles,PUBCHEM_CID,PUBCHEM_ACTIVITY_OUTCOME
0,C1C(CC(=O)C2=CN=C(N=C21)NC(=O)C3=CC=CO3)C4=CC=...,6603008,Inactive
1,C1=CC=C(C=C1)S(=O)(=O)CC2=NC3=CC=CC=C3S2,6602571,Inactive
2,CC(=O)N1CCCC2=C1C=CC(=C2)S(=O)(=O)N(C)CCC#N,6602616,Inactive
3,CCC(C)NC(=O)CCCCCN1C(=O)C2=CC(=C(C=C2NC1=O)OC)OC,644371,Inactive
4,CCOCCCNCC(=O)NC1=CC=C(C=C1)OC(F)(F)F.Cl,6603132,Inactive
...,...,...,...
42689,CC(C([C@H]1CNC2=C(N1)C(=O)NC(=N2)N)O)O,135409384,Inactive
42690,CN(C)CC[C@@H](C1=CC=C(C=C1)Br)C2=CC=CC=N2,16960,Inactive
42691,COC1=CC=CC=C1N2CCN(CC2)CCN(C3=CC=CC=N3)C(=O)C4...,6603915,Inactive
42692,CCCCCCCCC1=CC=C(C=C1)C2=CC=C(C=C2)C(=O)O,1714884,Inactive
42693,CC[C@H](C)[C@@H](C(=O)N[C@@H](C)C(=O)N[C@@H](C...,44290899,Inactive

In [ ]:
! pip install padelpy #padelpy to calculate descriptors

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting padelpy
  Downloading padelpy-0.1.11-py2.py3-none-any.whl (20.9 MB)
     |â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 20.9 MB 1.2 MB/s
Installing collected packages: padelpy
Successfully installed padelpy-0.1.11

In [ ]:
df.rename(columns = {'Smiles':'CANONICAL_SMILES'}, inplace = True)  # rename smile column as CANONICAL_SMILES
df

,cid,CANONICAL_SMILES,PUBCHEM_ACTIVITY_OUTCOME
0,187,CC(=O)OCC[N+](C)(C)C,Active
1,342,CC1=CC(=CC=C1)O,Active
2,791,CCC(C)C(C(=O)O)N,Active
3,857,CC(C)CC(C(=O)O)N,Active
4,938,C1=CC(=CN=C1)C(=O)O,Active
...,...,...,...
222,5464587,C1=CC(=CC=C1N=NC2=CC(=C(C=C2)N/N=C\3/C(=O)C4=C...,Active
223,11321048,C1CC(C1)(C(=O)O)N.Cl,Active
224,122525482,CC(C)C(=O)COCCOCCNC(=O)COCCOCCNC(=O)CC[C@@H](C...,Active
225,152743288,CC(C1=CC2=C(C=C1)C3C=C(C=CC3=N2)Cl)C(=O)O,Active
226,157242960,CC(C)C(=O)CNC(=O)CNC(=O)[C@H](CO)NC(=O)CNC(=O)...,Active

Compute desired decriptors

In [ ]:
! wget https://github.com/dataprofessor/padel/raw/main/fingerprints_xml.zip
! unzip fingerprints_xml.zip

--2022-07-16 11:17:09--  https://github.com/dataprofessor/padel/raw/main/fingerprints_xml.zip
Resolving github.com (github.com)... 140.82.113.3
Connecting to github.com (github.com)|140.82.113.3|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://raw.githubusercontent.com/dataprofessor/padel/main/fingerprints_xml.zip [following]
--2022-07-16 11:17:10--  https://raw.githubusercontent.com/dataprofessor/padel/main/fingerprints_xml.zip
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 10871 (11K) [application/zip]
Saving to: â€˜fingerprints_xml.zipâ€™

fingerprints_xml.zi 100%[===================>]  10.62K  --.-KB/s    in 0s

2022-07-16 11:17:10 (51.5 MB/s) - â€˜fingerprints_xml.zipâ€™ saved [10871/10871]

Archive:  fingerprints_xml.zip
  inflating: AtomPairs2DFingerprintCount.xml
  inflating: AtomPairs2DFingerprinter.xml
  inflating: EStateFingerprinter.xml
  inflating: ExtendedFingerprinter.xml
  inflating: Fingerprinter.xml
  inflating: GraphOnlyFingerprinter.xml
  inflating: KlekotaRothFingerprintCount.xml
  inflating: KlekotaRothFingerprinter.xml
  inflating: MACCSFingerprinter.xml
  inflating: PubchemFingerprinter.xml
  inflating: SubstructureFingerprintCount.xml
  inflating: SubstructureFingerprinter.xml

In [ ]:
import glob 
xml_files = glob.glob("*.xml") #return file paths named .xml
xml_files.sort()
xml_files

['AtomPairs2DFingerprintCount.xml',
 'AtomPairs2DFingerprinter.xml',
 'EStateFingerprinter.xml',
 'ExtendedFingerprinter.xml',
 'Fingerprinter.xml',
 'GraphOnlyFingerprinter.xml',
 'KlekotaRothFingerprintCount.xml',
 'KlekotaRothFingerprinter.xml',
 'MACCSFingerprinter.xml',
 'PubchemFingerprinter.xml',
 'SubstructureFingerprintCount.xml',
 'SubstructureFingerprinter.xml']

In [ ]:
#create a list and assign them to the xml files( to compute descriptors)
FP_list = ['AtomPairs2DCount',
 'AtomPairs2D',
 'EState',
 'CDKextended',
 'CDK',
 'CDKgraphonly',
 'KlekotaRothCount',
 'KlekotaRoth',
 'MACCS',
 'PubChem',
 'SubstructureCount',
 'Substructure']

In [ ]:
fp = dict(zip(FP_list, xml_files)) #create a dictionary of all..
fp

{'AtomPairs2D': 'AtomPairs2DFingerprinter.xml',
 'AtomPairs2DCount': 'AtomPairs2DFingerprintCount.xml',
 'CDK': 'Fingerprinter.xml',
 'CDKextended': 'ExtendedFingerprinter.xml',
 'CDKgraphonly': 'GraphOnlyFingerprinter.xml',
 'EState': 'EStateFingerprinter.xml',
 'KlekotaRoth': 'KlekotaRothFingerprinter.xml',
 'KlekotaRothCount': 'KlekotaRothFingerprintCount.xml',
 'MACCS': 'MACCSFingerprinter.xml',
 'PubChem': 'PubchemFingerprinter.xml',
 'Substructure': 'SubstructureFingerprinter.xml',
 'SubstructureCount': 'SubstructureFingerprintCount.xml'}

In [ ]:
fp['AtomPairs2D']

'AtomPairs2DFingerprinter.xml'

In [ ]:
from padelpy import padeldescriptor   #import downloaded padel descriptor
df2 = pd.concat( [df['CANONICAL_SMILES'],df['cid']], axis=1 )  #extract smiles and cid columns from dataframe and add to df2
df2.to_csv('/content/drive/MyDrive/final_project/molecule.smi', sep='\t', index=False, header=False) #save to csv file without headers and index
df2.to_csv('/content/drive/MyDrive/final_project/molecule2.smi', sep='\t', index=False, header=False)
df2

                                      CANONICAL_SMILES        cid
0                                 CC(=O)OCC[N+](C)(C)C        187
1                                      CC1=CC(=CC=C1)O        342
2                                     CCC(C)C(C(=O)O)N        791
3                                     CC(C)CC(C(=O)O)N        857
4                                  C1=CC(=CN=C1)C(=O)O        938
..                                                 ...        ...
222  C1=CC(=CC=C1N=NC2=CC(=C(C=C2)N/N=C\3/C(=O)C4=C...    5464587
223                               C1CC(C1)(C(=O)O)N.Cl   11321048
224  CC(C)C(=O)COCCOCCNC(=O)COCCOCCNC(=O)CC[C@@H](C...  122525482
225          CC(C1=CC2=C(C=C1)C3C=C(C=CC3=N2)Cl)C(=O)O  152743288
226  CC(C)C(=O)CNC(=O)CNC(=O)[C@H](CO)NC(=O)CNC(=O)...  157242960

[227 rows x 2 columns]

In [ ]:
dat = pd.read_csv('/content/drive/MyDrive/final_project/molecule2.smi')

In [ ]:
dat

                             CC(=O)OCC[N+](C)(C)C\t187
0                                 CC1=CC(=CC=C1)O\t342
1                                CCC(C)C(C(=O)O)N\t791
2                                CC(C)CC(C(=O)O)N\t857
3                             C1=CC(=CN=C1)C(=O)O\t938
4                         C1=CC(=C(C=C1C(CN)O)O)O\t951
..                                                 ...
221  C1=CC(=CC=C1N=NC2=CC(=C(C=C2)N/N=C\3/C(=O)C4=C...
222                     C1CC(C1)(C(=O)O)N.Cl\t11321048
223  CC(C)C(=O)COCCOCCNC(=O)COCCOCCNC(=O)CC[C@@H](C...
224  CC(C1=CC2=C(C=C1)C3C=C(C=CC3=N2)Cl)C(=O)O\t152...
225  CC(C)C(=O)CNC(=O)CNC(=O)[C@H](CO)NC(=O)CNC(=O)...

[226 rows x 1 columns]

In [ ]:
from padelpy import padeldescriptor

fingerprint = 'PubChem' #computing pubchem descriptors

fingerprint_output_file = ''.join([fingerprint,'.csv']) #Compute descriptor using [DescriptorName.csv]eg PubChem.csv or Substructure.csv
fingerprint_descriptortypes = fp[fingerprint]

padeldescriptor(mol_dir='/content/drive/MyDrive/final_project/molecule2.smi', 
                d_file=fingerprint_output_file, #'Substructure.csv'
                #descriptortypes='SubstructureFingerprint.xml', 
                descriptortypes= fingerprint_descriptortypes,
                detectaromaticity=True,
                standardizenitro=True,
                standardizetautomers=True,
                threads=2,
                removesalt=True,
                log=True,
                fingerprints=True)

In [ ]:
desc = pd.read_csv('PubChem.csv') #read calculated descriptors saved as PubChem.csv
desc.to_csv('/content/drive/MyDrive/final_project/dataset_descriptor2.csv', index=False)   #save a s a separate csv file for API usage

In [ ]:
desc = pd.read_csv('PubChem_major.csv')
import numpy as np
desc = desc.apply(np.int64) #convert all folats to integres
desc.to_csv('/content/drive/MyDrive/final_project/dataset_descriptor1.csv', index=False)

In [ ]:
desc

,Name,PubchemFP0,PubchemFP1,PubchemFP2,PubchemFP3,PubchemFP4,PubchemFP5,PubchemFP6,PubchemFP7,PubchemFP8,...,PubchemFP871,PubchemFP872,PubchemFP873,PubchemFP874,PubchemFP875,PubchemFP876,PubchemFP877,PubchemFP878,PubchemFP879,PubchemFP880
0,6602571,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,6603008,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,6602616,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,6603132,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,644371,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
42689,135409384,1,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42690,16960,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42691,1714884,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42692,6603915,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
42693,44290899,1,1,1,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0